
[1] = { 'File', ' ', 'Tag' },
[2] = { 'Module', ' ', 'Exception' },
[3] = { 'Namespace', ' ', 'Include' },
[4] = { 'Package', ' ', 'Label' },
[5] = { 'Class', ' ', 'Include' },
[6] = { 'Method', 'M ', 'Function' },
[7] = { 'Property', ' ', '@property' },
[8] = { 'Field', ' ', '@field' },
[9] = { 'Constructor', ' ', '@constructor' },
[10] = { 'Enum', ' ', '@number' },
[11] = { 'Interface', 'ﰮ ', 'Type' },
[12] = { 'Function', ' ', 'Function' },
[13] = { 'Variable', ' ', '@variable' },
[14] = { 'Constant', ' ', 'Constant' },
[15] = { 'String', '󰅳 ', 'String' },
[16] = { 'Number', ' ', 'Number' },
[17] = { 'Boolean', 'B ', 'Boolean' },
[18] = { 'Array', '󰅨 ', 'Type' },
[19] = { 'Object', ' ', 'Type' },
[20] = { 'Key', ' ', '' },
[21] = { 'Null', '󰟢 ', 'Constant' },
[22] = { 'EnumMember', ' ', 'Number' },
[23] = { 'Struct', ' ', 'Type' },
[24] = { 'Event', ' ', 'Constant' },
[25] = { 'Operator', ' ', 'Operator' },
[26] = { 'TypeParameter', ' ', 'Type' },
-- ccls
[252] = { 'TypeAlias', ' ', 'Type' },
[253] = { 'Parameter', ' ', '@parameter' },
[254] = { 'StaticMethod', ' ', 'Function' },
[255] = { 'Macro', ' ', 'Macro' },
-- for completion sb microsoft!!!
[300] = { 'Text', ' ', 'String' },
[301] = { 'Snippet', ' ', '@variable' },
[302] = { 'Folder', ' ', 'Title' },
[303] = { 'Unit', ' ', 'Number' },


icons = {
	Class = " ",
	Color = " ",
	Constant = " ",
	Constructor = " ",
	Enum = "了 ",
	EnumMember = " ",
	Field = " ",
	File = " ",
	Folder = " ",
	Function = " ",
	Interface = "ﰮ ",
	Keyword = " ",
	Method = "a ",
	Module = " ",
	Property = " ",
	Snippet = "﬌ ",
	Struct = " ",
	Text = " ",
	Unit = " ",
	Value = " ",
	Variable = " ",
}
  local kind = {
    [1] = { 'File', ' ', 'Tag' },
    [2] = { 'Module', ' ', 'Exception' },
    [3] = { 'Namespace', ' ', 'Include' },
    [4] = { 'Package', ' ', 'Label' },
    [5] = { 'Class', ' ', 'Include' },
    [6] = { 'Method', ' ', 'Function' },
    [7] = { 'Property', ' ', '@property' },
    [8] = { 'Field', ' ', '@field' },
    [9] = { 'Constructor', ' ', '@constructor' },
    [10] = { 'Enum', '了', '@number' },
    [11] = { 'Interface', ' ', 'Type' },
    [12] = { 'Function', ' ', 'Function' },
    [13] = { 'Variable', ' ', '@variable' },
    [14] = { 'Constant', ' ', 'Constant' },
    [15] = { 'String', ' ', 'String' },
    [16] = { 'Number', ' ', 'Number' },
    [17] = { 'Boolean', ' ', 'Boolean' },
    [18] = { 'Array', ' ', 'Type' },
    [19] = { 'Object', ' ', 'Type' },
    [20] = { 'Key', ' ', '' },
    [21] = { 'Null', ' ', 'Constant' },
    [22] = { 'EnumMember', ' ', 'Number' },
    [23] = { 'Struct', ' ', 'Type' },
    [24] = { 'Event', ' ', 'Constant' },
    [25] = { 'Operator', ' ', 'Operator' },
    [26] = { 'TypeParameter', ' ', 'Type' },
    -- ccls
    [252] = { 'TypeAlias', ' ', 'Type' },
    [253] = { 'Parameter', ' ', '@parameter' },
    [254] = { 'StaticMethod', 'ﴂ ', 'Function' },
    [255] = { 'Macro', ' ', 'Macro' },
    -- for completion sb microsoft!!!
    [300] = { 'Text', ' ', 'String' },
    [301] = { 'Snippet', ' ', '@variable' },
    [302] = { 'Folder', ' ', '@parameter' },
    [303] = { 'Unit', ' ', 'Number' },
    [304] = { 'Value', ' ', '@variable' },
  }

